services:
  django_web:
    image: my-workflow-plus:v0.1.0
    build:
      context: .
      dockerfile: docker/Dockerfile
    ports:
      - "${APP_PORT}:8000"
    environment:
      - DJANGO_SECRET_KEY: ${DJANGO_SECRET_KEY}
      - DJANGO_ALLOWED_HOSTS: ${DJANGO_ALLOWED_HOSTS}
      - DJANGO_DATABASE_URL: ${DJANGO_DATABASE_URL}
      - DJANGO_DEBUG: ${DJANGO_DEBUG}
      env_file:
        - .env
